services:
  museum:
    image: ghcr.io/ente-io/server
    ports:
      # - "127.0.0.1:${MUSEUM_PORT}:8080" # API
      - "${MUSEUM_PORT}:8080" # API
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./museum.yaml:/museum.yaml:ro
      - ./.docker_data/museum:/data:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/ping"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 120s
        #    labels:
        #      traefik.enable: 'true'
        #      traefik.http.routers.ente-web-api.rule: 'Host(`${API_DOMAIN?err}`)'
        #      traefik.http.routers.ente-web-api.entrypoints: 'websecure'
        #      traefik.http.routers.ente-web-api.tls.certResolver: 'default'
        #      traefik.http.services.ente-web-api.loadbalancer.server.port: '8080'

  # Resolve "localhost:3200" in the museum container to the minio container.
  socat:
    image: alpine/socat
    network_mode: service:museum
    depends_on: [museum]
    command: "TCP-LISTEN:3200,fork,reuseaddr TCP:minio:3200"

  web:
    image: ghcr.io/ente-io/web
    # Uncomment what you need to tweak.
    ports:
      # - 3000:3000 # Photos web app
      - "${ACCOUNTS_PORT}:3001" # Accounts
      # - 3002:3002 # Public albums
      # - "127.0.0.1:${AUTH_PORT}:3003" # Auth
      - "${AUTH_PORT}:3003" # Auth
      # - 3004:3004 # Cast
      # - 3005:3005 # Share
      # - 3006:3006 # Embed
    # Modify these values to your custom subdomains, if using any
    environment:
      ENTE_API_ORIGIN: ${API_ORIGIN}
      # ENTE_ALBUMS_ORIGIN: https://localhost:3002
      # ENTE_PHOTOS_ORIGIN: https://localhost:3000
      #    labels:
      #      traefik.enable: 'true'
      #      traefik.http.routers.ente-web.rule: 'Host(`${WEB_DOMAIN?err}`)'
      #      traefik.http.routers.ente-web.entrypoints: 'websecure'
      #      traefik.http.routers.ente-web.tls.certResolver: 'default'
      #      traefik.http.services.ente-web.loadbalancer.server.port: '3003'

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    healthcheck:
      test: pg_isready -q -d ${PG_DB} -U ${PG_USER}
      start_period: 40s
      start_interval: 1s
    volumes:
      - ./.docker_data/postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - 3200:3200 # MinIO API
      # Uncomment to enable MinIO Web UI      
      # - 3201:3201
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASS}
    command: server /data --address ":3200" --console-address ":3201"
    volumes:
      - ./.docker_data/minio-data:/data
    post_start:
      - command: |
          sh -c '
          #!/bin/sh

          while ! mc alias set h0 http://minio:3200 ${MINIO_USER} ${MINIO_PASS} 2>/dev/null
          do
            echo "Waiting for minio..."
            sleep 0.5
          done

          cd /data

          mc mb -p b2-eu-cen
          mc mb -p wasabi-eu-central-2-v3
          mc mb -p scw-eu-fr-v3
          '

volumes:
  postgres-data:
  minio-data:
